version: '2'
services:
  database:
   image: postgres
   restart: always
   environment:
    - "POSTGRES_PASSWORD=mysecretpassword"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_DB=postgres"
   ports:
   - 5433:5432
   container_name: database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
   build:
     context: "."
     dockerfile: Dockerfile_API
   depends_on:
    - database
   volumes:
     - "$PWD/../backend:/backend"
   ports:
    - "8000:8000"
   command: python3 /backend/manage.py runserver 0.0.0.0:8000 #--db_url database --db_port 5432

  picture_server:
    build:
     context: "."
     dockerfile: Dockerfile_Pictureserver
    volumes:
      - "$PWD/pictures/:/usr/local/apache2/htdocs/"
    ports:
     - "8081:80"

