version: '2'
services:
  database:
   image: postgres
   environment:
    - "POSTGRES_PASSWORD=mysecretpassword"
   container_name: database

  api:
   image: python:3.7.1-alpine3.8
   depends_on:
    - database
   volumes:
     - "$PWD/../backend:/backend"
   command: python3 /backend/main.py #--db_url database --db_port 5432
