FROM ubuntu:18.10

RUN apt-get update && apt-get install -y python3 python3-pip

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . /backend/

CMD ["python3", "/backend/manage.py", "runserver", "0.0.0.0:8000"]