# Generated by Django 2.1.4 on 2018-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('dataset', models.ManyToManyField(to='data_sets.DataSet')),
            ],
        ),
    ]
