# Generated by Django 2.1.4 on 2018-12-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=4096)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sets.DataSet')),
            ],
        ),
    ]
