# Generated by Django 2.1.2 on 2018-12-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='customer',
            new_name='data_set',
        ),
    ]
