# Generated by Django 2.1.4 on 2018-12-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potential_labels', '0002_remove_potentiallabel_dataset'),
        ('data_sets', '0002_dataset_potential_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='potential_label',
        ),
        migrations.AddField(
            model_name='dataset',
            name='potential_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='potential_labels.PotentialLabel'),
            preserve_default=False,
        ),
    ]
