# Generated by Django 2.1.4 on 2018-12-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sets', '0003_dataset_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
