# Generated by Django 2.1.4 on 2018-12-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potential_labels', '0001_initial'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='potential_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='potential_labels.PotentialLabel'),
            preserve_default=False,
        ),
    ]
